spring:
  application:
    name: asset_backend

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/asset_db
    username: asset_user
    password: asset1234
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Server
server:
  port:

claude:
  api:
    key: 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