spring:
  application:
    name: asset_backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
server:
  port: 8080
claude:
  api:
    key: ${ANTHROPIC_API_KEY}
jwt:
  secret: ${JWT_SECRET}

cookie:
  secure: true
  domain: .yoojoo-asset-management.xyz

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  google-rss:
    base-url: ${GOOGLE_RSS_BASE_URL}

openai:
  api-key: ${OPENAI_API_KEY}
  embedding-url: ${OPENAI_EMBEDDING_URL}

pinecone:
  api-key: ${PINECONE_API_KEY}
  host: ${PINECONE_HOST}
  index-name: ${PINECONE_INDEX_NAME}